# Generated by Django 3.1.3 on 2021-01-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_user',
            new_name='user',
        ),
    ]
