# Generated by Django 3.1.3 on 2021-03-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210129_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='listening.png', upload_to='images/'),
        ),
    ]
