# Generated by Django 3.1.3 on 2021-03-07 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210302_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, upload_to='posts', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
    ]
