# Generated by Django 3.1.3 on 2021-03-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20210302_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='', max_length=200)),
                ('artist_name2', models.CharField(default='', max_length=200)),
                ('artist_name3', models.CharField(default='', max_length=200)),
                ('artist_name4', models.CharField(default='', max_length=200)),
                ('artist_name5', models.CharField(default='', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('as_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('as_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='accounts.userprofile')),
            ],
        ),
    ]
