# Generated by Django 3.1.3 on 2021-03-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210302_2251'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='as_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='as_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='accounts.userprofile'),
        ),
    ]
