# Generated by Django 3.1.3 on 2021-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_album_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
